### PR TITLE
Spider first steps ...

### PR DESCRIPTION
**Pull request by lwm**
This is my current progress for now. Things still to do:

- [x] Write the crawlers/README.md (and do it first next time)
- [x] Write all the docstrings
- [x] Add tests
- [x] Split up commits for proper review

@arsenal9971 

I have got as far as to create the pipeline where you will receive HTML for parsing. It's [here][1].

~~When I get the above tasks done, I will let you know - it will also be clearer :)~~

Ref #9 

[1]: https://github.com/WorldBrain/crawler/compare/WorldBrain:90f8d3f...WorldBrain:8e2a4bb#diff-32ca4eb1ae4945234eff04c0afb2c570R12

### CODE REVIEW

**Comment by lwm** [comment]
@oliversauter @arsenal9971 @dev-tim 

Can you all give that review and see if it makes sense?

@arsenal9971

You should be able to move forward with the parsing in `pipelines.py`. Any tests you need to write can be placed in the `test/` folder.

I'll work on review comments here and then bring the Django app. Let me know if anything is unclear.

**Comment by oliversauter** [comment]
@lwm It is unclear to me what the Articlespider does on a high level: 
**From your readme:**
>ArticleSpider
>This directory contains the source for the ArticleSpider.

Can you add 1-2 sentences describing this?

**Comment by oliversauter** [comment]
@lwm could be as simple as: 

#### Goal of module:
This Module does this and this 

#### Input:
#### Output:

**Comment by lwm** [comment]
> @lwm It is unclear to me what the Articlespider does on a high level: 

Covered it [here][1].

[1]: https://github.com/WorldBrain/crawler/pull/10/files#diff-eca4f09cec5788b2eba2a8dae597b42eR27

**Comment by oliversauter** [comment]
Yeah well, those descriptions are actually very technically specific. 
It took me reading the whole thing in order to understand which part of the process it actually is. 

To be expected would be a high level description of the whole module at the beginning, so that people don't have to read the descriptions of all the elements in order to understand what is happening. 
**My suggestion for the next time:**
 1. When describing any module AND submodule(like `pipelines.py`), I would include 4 paragraphs: 
     - a high level definition of what it does WHEN FINISHED (explain it like I am 5)
     - a technical description of what it does WHEN FINISHED (like yours) and 
     - Input/Output
     - the current state of the development of that (sub)module / ToDos:


**As an example of the whole ArticleSpider module:**
#### Goal of module:
This module crawls all URLs for a given domain and filters out those who are unlikely to be articles, it then parses those URLs for its HTML content and returns... (_**what?**_)

#### Technical Implementation:

#### Input:
List of domains 

#### Output:
 1. (A string containing the HTML code for each URL that has been identified as article) _**is it that?**_
 2. A .txt file containing all the urls that have been filtered out and are likely to be **no** articles. 

#### Current State/To-Dos

This is the current state. blalbalbala

**Still to do:** 

- [ ] 
- [ ] 
- [ ] 

Something along those lines. 



## Other questions: 
> I expect all our parsing logic to be contained within pipelines.py.

What do you mean by that? Are we now talking about parsing just the HTML or the specific content points?


PS: I know I am being anal (new word I learned recently. Who the hell invented using this word like that 😄 ) with the documentation. It's important that we get to the point where people just come and instantly understand what we are doing on every level. It will take time, but I am sure we'll get there!
Thats what different views and more pair of eyes are there for...to improve each other :)

Keep it up! Thanks for your work! :)

**Comment by lwm** [comment]
@oliversauter 

Sounds like good recommendations. I will work to improve the documentation.

In the mean time, I will merge this when it goes green as I added my tests.

**Comment by lwm** [comment]
Closes #9 for now.

**Comment by lwm** [comment]
ugh, Travis is stalled ... merging as I don't want to block on this. All tests passing locally.

**Pull request merged**
